version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: workshop
      POSTGRES_USER: workshop
      POSTGRES_DB: workshop
    ports:
    - 5432:5432
